web/router.ex
defmodule MsqhPortal.Router do
  use MsqhPortal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MsqhPortal.Auth, repo: MsqhPortal.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_layout do
    plug MsqhPortal.Notification, repo: MsqhPortal.Repo
    plug :put_layout, {MsqhPortal.LayoutView, :admin}
  end

  pipeline :user_layout do
    plug MsqhPortal.Notification, repo: MsqhPortal.Repo
    plug :put_layout, {MsqhPortal.LayoutView, :user}
  end

  pipeline :login_layout do
    plug :put_layout, {MsqhPortal.LayoutView, :login}
  end

  pipeline :register_layout do
    plug :put_layout, {MsqhPortal.LayoutView, :register}
  end

  scope "/", MsqhPortal do
    pipe_through [:browser, :login_layout]

    get "/", LoginController, :index
    get "/change", LoginController, :change
    post "/send_email", LoginController, :change_password
    get "/reset/:id", LoginController, :reset
    get "/admin", AdminLoginController, :index
    get "/admin/change", AdminLoginController, :change
  end

  scope "/register", MsqhPortal do
    pipe_through [:browser, :register_layout]

    get "/", UserController, :new
    get "/admin", AdminController, :new
    post "/admin", AdminController, :create
    post "/", UserController, :create
  end

  scope "/", MsqhPortal do
    pipe_through [:browser, :user_layout] # Use the default browser stack

    resources "/user_enquiries", UserEnquiryController
    get "/user_enquiries/reply/:id", UserEnquiryController, :reply
    post "/user_enquiries/reply", UserEnquiryController, :send_reply
    patch "/user_enquiries/:id", UserEnquiryController, :response
    put "/user_enquiries/:id", UserEnquiryController, :response

    resources "/payments", PaymentController
    resources "/memberships", MembershipController
    resources "/facilities", FacilityController
    resources "/dashboard", UserController, only: [:index]
    get "/profile", ProfileController, :index
    get "/profile/edit", ProfileController, :edit
    patch "/profile/:id", ProfileController, :update
    put "/profile/:id", ProfileController, :update
    get "/payment", UserPaymentController, :index
    resources "/membership", UserMembershipController, only: [:index, :new, :create]
    get "/membership/edit/:id", UserMembershipController, :edit
    patch "/membership/:id", UserMembershipController, :update
    put "/membership/:id", UserMembershipController, :update
    resources "/membership/payment", UserMembershipPaymentController, only: [:index, :new, :create, :show]
    get "/membership/payment/edit/:id", UserMembershipPaymentController, :edit
    patch "/membership/payment/:id", UserMembershipPaymentController, :update
    put "/membership/payment/:id", UserMembershipPaymentController, :update
    get "/help", HelpController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/activation/:confirm_id", ActivationController, :confirm
    get "/events", UserEventController, :index
    get "/vouchers", UserRebateController, :index
    get "/resources", UserResourceController, :index

  end

  scope "/admin", MsqhPortal do
    pipe_through [:browser, :admin_layout] # Use the default browser stack

    resources "/dashboard", AdminController, only: [:index, :new, :show, :delete, :update, :create]
    get "/dashboard/change/:id", AdminController, :change
    put "/dashboard/change_password/:id", AdminController, :change_password
    get "/dashboard/edit/:id", AdminController, :edit
    resources "/prices", DefaultPriceController
    resources "/notifications", AdminMembershipSettingController
    resources "/membership_type", MembershipTypeController
    resources "/membership_category", MembershipCategoryController
    resources "/payments", PaymentLogController
    post "/search", AdminController, :search
    get "/approve/:id", AdminController, :approve
    patch "/approve/:id", AdminController, :approve
    put "/approve/:id", AdminController, :approve
    put "/verify/payment", AdminController, :verify
    post "/verify/payment", AdminController, :verify
    resources "/facilities", AdminFacilityController, only: [:index, :new, :show, :delete, :update, :create]
    get "/facilities/edit/:id", AdminFacilityController, :edit
    get "/facilities/package/edit/:id", AdminFacilityController, :edit_package
    patch "/facilities/package/update/:id", AdminFacilityController, :update_package
    put "/facilities/package/update/:id", AdminFacilityController, :update_package
    get "/settings", AdminSettingController, :index
    put "/settings/expiration_notification", AdminSettingController, :edit_expiration_notification
    post "/settings/membership_type", AdminSettingController, :create_membership_type
    post "/settings/membership_category", AdminSettingController, :create_membership_category
    post "/settings/default_price", AdminSettingController, :create_default_price
    post "/settings/payment_type", AdminSettingController, :create_payment_type
    delete "/settings/admin/:id", AdminSettingController, :delete_admin
    patch "/settings/payment_type/:id", AdminSettingController, :update_payment_type
    put "/settings/payment_type/:id", AdminSettingController, :update_payment_type
    post "/settings/admin", AdminSettingController, :create_admin
    get "/rebates", AdminRebateController, :index
    resources "/events", AdminEventController, only: [:index, :new, :show, :delete, :update, :create]
    get "/events/edit/:id", AdminEventController, :edit
    post "/events/voucher/create", AdminEventController, :voucher_create
    resources "/manage/vouchers", VoucherController
    resources "/enquiries", AdminEnquiryController
    get "/enquiries/reply/:id", AdminEnquiryController, :reply
    post "/enquiries/reply", AdminEnquiryController, :send_reply
    resources "/manage/responses", EnquiryResponseController
    resources "/resources", AdminResourceController, only: [:index, :new, :show, :delete, :update, :create]
    get "/resources/edit/:id", AdminResourceController, :edit
    resources "/manage/resources/permissions", ResourcePermissionsController
    resources "/packages", PackageController, only: [:index, :new, :show, :delete, :update, :create]
    get "/packages/edit/:id", PackageController, :edit

    resources "/sessions", AdminSessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MsqhPortal do
  #   pipe_through :api
  # end
end

web/controllers/admin_setting_controller.ex
defmodule MsqhPortal.AdminSettingController do
  use MsqhPortal.Web, :controller

  alias MsqhPortal.MembershipCategory
  alias MsqhPortal.MembershipType
  alias MsqhPortal.DefaultPrice
  alias MsqhPortal.Facility
  alias MsqhPortal.PaymentType
  alias MsqhPortal.MembershipSetting
  alias MsqhPortal.User

  plug :load_membership_categories when action in [:index]
  plug :load_membership_types when action in [:index]

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
          [conn, conn.params])
  end

  @doc """
  Send email when:
  - Verifying user/admin after they have registered
  - {VARIABLE} day(s) before user membership is expired
  - When user creates a new ENQUIRY
  - When user creates a new PAYMENT / MEMBERSHIP
  - When new EVENT is created (Optional)
  """
  def index(conn, _) do
    payment_type_changeset = PaymentType.changeset(%PaymentType{})
    membership_category_changeset = MembershipCategory.changeset(%MembershipCategory{})
    membership_type_changeset = MembershipType.changeset(%MembershipType{})
    default_price_changeset = DefaultPrice.changeset(%DefaultPrice{})
    register_changeset = User.admin_registration_changeset(%User{})

    membership_categories = Repo.all(MembershipCategory)
    membership_types = Repo.all(MembershipType)
    payment_types = Repo.all(PaymentType)
    default_prices = Repo.all from m in DefaultPrice, preload: [:membership_category, :membership_type]
    facilities = Repo.all(Facility)
    membership_setting = Repo.get!(MembershipSetting, 1)
    membership_setting_changeset = MembershipSetting.changeset(membership_setting)
    admins = Repo.all from m in User, where: m.state == "ADMIN", order_by: [asc: m.username]

    render(conn, :index, payment_type_changeset: payment_type_changeset, membership_categories: membership_categories,
    membership_types: membership_types, default_prices: default_prices, payment_types: payment_types, facilities: facilities,
    membership_category_changeset: membership_category_changeset, membership_type_changeset: membership_type_changeset,
    default_price_changeset: default_price_changeset, membership_setting_changeset: membership_setting_changeset, admins: admins,
    register_changeset: register_changeset)
  end

  def edit_expiration_notification(conn, %{"membership_setting" => membership_setting_params}) do
    changeset = MembershipSetting.changeset(%MembershipSetting{id: 1}, membership_setting_params)

    case Repo.update(changeset) do
      {:ok, _membership_setting} ->
        conn
        |> put_flash(:info, "Notification setting created successfully.")
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, changeset} ->
        render(conn, "index.html", changeset: changeset)
    end
  end

  def create_membership_type(conn, %{"membership_type" => membership_type}) do
    changeset = MembershipType.changeset(%MembershipType{}, membership_type)
    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Membership type created successfully.")
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, changeset} ->
        render(conn, "index.html", changeset: changeset)
    end
  end

  def create_membership_category(conn, %{"membership_category" => membership_category}) do
    changeset = MembershipCategory.changeset(%MembershipCategory{}, membership_category)
    case Repo.insert(changeset) do
      {:ok, _user} ->
        IO.puts "inside create membership category"
        conn
        |> put_flash(:info, "Membership category created successfully.")
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, changeset} ->
        render(conn, "index.html", changeset: changeset)
    end
  end

  def create_payment_type(conn, %{"payment_type" => payment_type_params}) do
    changeset = PaymentType.changeset(%PaymentType{}, payment_type_params)

    case Repo.insert(changeset) do
      {:ok, _facility} ->
        conn
        |> put_flash(:info, "Payment Type created successfully.")
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, _changeset} ->
        payment_type_changeset = PaymentType.changeset(%PaymentType{})
        render(conn, "index.html", payment_type_changeset: payment_type_changeset)
    end
  end

  def create_default_price(conn, %{"default_price" => default_price_params}) do
    changeset = DefaultPrice.changeset(%DefaultPrice{}, default_price_params)

    case Repo.insert(changeset) do
      {:ok, _facility} ->
        conn
        |> put_flash(:info, "Default price created successfully.")
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, changeset} ->
        render(conn, "index.html", changeset: changeset)
    end
  end

  def update_payment_type(conn, %{"id" => id, "payment_type" => payment_type_params}) do
    payment_type = Repo.get!(PaymentType, id)
    changeset = PaymentType.changeset(payment_type, payment_type_params)

    case Repo.update(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Payment Type updated successfully.")
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, changeset} ->
        render(conn, "edit.html", payment_type: payment_type, changeset: changeset)
    end
  end

  def delete_admin(conn, %{"id" => id}) do
    admin = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(admin)

    conn
    |> put_flash(:info, "Admin deleted successfully.")
    |> redirect(to: admin_setting_path(conn, :index))
  end

  def create_admin(conn, %{"user" => user_params}) do
    changeset = User.admin_registration_changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        MsqhPortal.Email.verify_email(user.email, user.confirm_id) |> MsqhPortal.Mailer.deliver_later
        conn
        |> put_flash(:info, "Please confirm your email address: " <> user.email)
        |> redirect(to: admin_setting_path(conn, :index))
      {:error, _changeset} ->
        render(conn, "index.html")
    end
  end

  defp load_membership_types(conn, _) do
    query =
    MembershipType
    |> MembershipType.alphebetical
    |> MembershipType.names_and_ids
    membership_types_list = Repo.all query
    assign(conn, :membership_types_list, membership_types_list)
  end

  defp load_membership_categories(conn, _) do
    query =
    MembershipCategory
    |> MembershipCategory.alphebetical
    |> MembershipCategory.names_and_ids
    membership_categories_list = Repo.all query
    assign(conn, :membership_categories_list, membership_categories_list)
  end
end

web/views/admin_setting_view.ex
defmodule MsqhPortal.AdminSettingView do
  use MsqhPortal.Web, :view
end

web/templates/admin_setting/default_price.html.eex
<%= form_for @changeset, @action, [class: "ui form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :membership_category_id, "Membership Category", class: "control-label" %>
    <%= select f, :membership_category_id, @membership_categories, class: "ui fluid dropdown", prompt: "Membership Category" %>
    <%= error_tag f, :membership_category_id %>
  </div>

  <div class="field">
    <%= label f, :membership_type_id, "Membership Type", class: "control-label" %>
    <%= select f, :membership_type_id, @membership_types, class: "ui fluid dropdown", prompt: "Membership Type" %>
    <%= error_tag f, :membership_type_id %>
  </div>

  <div class="field">
    <%= label f, :life_membership_price, "Life Membership Price (RM)", class: "control-label" %>
    <%= text_input f, :life_membership_price, class: "form-control" %>
    <%= error_tag f, :life_membership_price %>
  </div>

  <div class="field">
    <%= label f, :new_member_annual_price, "New Member Annual Price (RM)", class: "control-label" %>
    <%= text_input f, :new_member_annual_price, class: "form-control" %>
    <%= error_tag f, :new_member_annual_price %>
  </div>

  <div class="field">
    <%= label f, :renewal_existing_member_annual_price, "Renewal Existing Member Annual Price (RM)", class: "control-label" %>
    <%= text_input f, :renewal_existing_member_annual_price, class: "form-control" %>
    <%= error_tag f, :renewal_existing_member_annual_price %>
  </div>

  <div class="field">
    <%= submit html_escape({:safe,"<i class='plus icon'></i>Default Price"}), class: "ui pink submit button" %>
  </div>
<% end %>

web/templates/admin_setting/edit_notify_user.html.eex
<%= form_for @changeset, @action, [class: "ui form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :days_before_notify_expiration, "Days before notify member of expiration", class: "control-label" %>
    <%= text_input f, :days_before_notify_expiration, class: "form-control" %>
    <%= error_tag f, :days_before_notify_expiration %>
  </div>

  <div class="field">
    <%= submit html_escape({:safe,"<i class='edit icon'></i>Save"}), class: "ui pink submit button" %>
  </div>
<% end %>

web/templates/admin_setting/index.html.eex
<div class="ui grid">
  <div class="six wide column">
    <div class="ui breadcrumb">
      <%= link "Dashboard", to: admin_path(@conn, :index) %>
      <div class="divider"> / </div>
      <div class="active section">Global Settings</div>
    </div>
    <h3 class="ui dividing header">
      <i class="large mail icon"></i>
      <div class="content">Email Notification Setup</div>
    </h3>
    <div class="ui segment">

      <%= render "edit_notify_user.html", changeset: @membership_setting_changeset,
                              action: admin_setting_path(@conn, :edit_expiration_notification) %>
    </div>
    <%= if @current_user.state == "SUPERADMIN" do %>
      <h3 class="ui dividing header">
        <i class="large users icon"></i>
        <div class="content">Admin Management</div>
      </h3>
      <%= if Enum.count(@admins) > 0 do %>
      <div class="ui segment">
        <!-- List of admins -->
        <%= for admin <- @admins do %>
        <div class="ui list">
          <div class="item">
            <img class="ui avatar image" src="/images/avatar-admin.png">
            <div class="content">
              <div class="header"><%= admin.username %></div>
              <div class="description"><%= admin.email %></div>
            </div>
            <div class="right floated content">
              <%= link html_escape({:safe, "<i class='large delete icon'></i>"}), to: admin_setting_path(@conn, :delete_admin, admin), method: :delete, data: [confirm: "Are you sure you want to delete " <> admin.username <> "?"],  class: "btn btn-default btn-xs" %>
            </div>
          </div>
        </div>
        <%= end %>
        <div class="ui divider"></div>
        <h4 class="ui dividing header">
          <i class="add user icon"></i>
          <div class="content">New admin</div>
        </h4>
          <p>
            <%= render "register.html", changeset: @register_changeset,
                                    action: admin_setting_path(@conn, :create_admin) %>
          </p>
      </div>
      <%= else %>
      <div class="ui segment">
        <p>No admin registered</p>
        <div class="ui divider"></div>
        <h4 class="ui dividing header">
          <i class="add user icon"></i>
          <div class="content">New admin</div>
        </h4>
          <p>
            <%= render "register.html", changeset: @register_changeset,
                                    action: admin_setting_path(@conn, :create_admin) %>
          </p>
      </div>
      <%= end %>
    <%= end %>
  </div>
  <div class="ten wide column">
    <h3 class="ui dividing header">
      <i class="large setting icon"></i>
      <div class="content">Global Defaults</div>
    </h3>
    <div class="ui secondary menu fluid steps">
      <a class="step item active" data-tab="membership-category">Membership Categories</a>
      <a class="step item" data-tab="membership-type">Membership Types</a>
      <a class="step item" data-tab="default-prices">Default Prices</a>
      <a class="step item" data-tab="facilities">Facilities</a>
      <a class="step item" data-tab="payment-methods">Payment Methods</a>
    </div>

    <div class="ui active tab segment" data-tab="membership-category">
      <h4 class="ui dividing header">Membership Categories</h4>
      <div class="ui relaxed list">
        <%= for membership_category <- @membership_categories do %>
        <div class="item">
          <i class="large caret right icon"></i>
          <div class="content">
            <div class="header">
              <div class="ui teal label">
                <%= membership_category.membership_category_name %>
              </div>
              <div class="ui yellow label">
                Created
                <div class="detail"><%= Timex.Timezone.convert(membership_category.updated_at, "Asia/Kuala_Lumpur") |>
                Timex.format!("%A, %b %d, %Y %l:%M%P", :strftime) %></div>
              </div>
            </div>
          </div>
        </div>
        <%= end %>
      </div>
      <h4 class="ui dividing header">Add Membership Category</h4>
      <%= render "membership_category.html", changeset: @membership_category_changeset,
                              action: admin_setting_path(@conn, :create_membership_category) %>
    </div>
    <div class="ui tab segment" data-tab="membership-type">
      <h4 class="ui dividing header">Membership Types</h4>
      <div class="ui relaxed list">
        <%= for membership_type <- @membership_types do %>
        <div class="item">
          <i class="large caret right icon"></i>
          <div class="content">
            <div class="header">
              <div class="ui teal label">
                <%= membership_type.membership_type_name %>
              </div>
              <div class="ui yellow label">
                Created
                <div class="detail"><%= Timex.Timezone.convert(membership_type.updated_at, "Asia/Kuala_Lumpur") |>
                Timex.format!("%A, %b %d, %Y %l:%M%P", :strftime) %></div>
              </div>
            </div>
          </div>
        </div>
        <%= end %>
      </div>
      <h4 class="ui dividing header">Add Membership Type</h4>
      <%= render "membership_type.html", changeset: @membership_type_changeset,
                              action: admin_setting_path(@conn, :create_membership_type)%>
    </div>
    <div class="ui tab segment" data-tab="default-prices">
      <h4 class="ui dividing header">Default Prices</h4>
        <div class="ui relaxed list">
          <%= for default_price <- @default_prices do %>
          <div class="item">
            <i class="large caret right icon"></i>
            <div class="content">
              <div class="header">
                <div class="ui blue label">
                  <%= unless is_nil(default_price.life_membership_price) do %>
                    <%= default_price.life_membership_price %>
                  <%= end %>
                  <%= unless is_nil(default_price.new_member_annual_price) do %>
                    <%= default_price.new_member_annual_price %>
                  <%= end %>
                  <%= unless is_nil(default_price.renewal_existing_member_annual_price) do %>
                    <%= default_price.renewal_existing_member_annual_price %>
                  <%= end %>
                </div>
                <%= unless is_nil(default_price.membership_category) do %>
                  <div class="ui teal label">
                    Category
                    <div class="detail">
                      <%= default_price.membership_category.membership_category_name %>
                    </div>
                  </div>
                  <%= end %>
                <%= unless is_nil(default_price.membership_type) do %>
                <div class="ui yellow label">
                  Type
                  <div class="detail"><%= default_price.membership_type.membership_type_name %></div>
                </div>
                <%= end %>
              </div>
            </div>
        </div>
        <%= end %>
      </div>
      <h4 class="ui dividing header">Add Default Price</h4>
      <%= render "default_price.html", changeset: @default_price_changeset,
                              action: admin_setting_path(@conn, :create_default_price),
                              membership_types: @membership_types_list,
                              membership_categories: @membership_categories_list %>
    </div>
    <div class="ui tab segment" data-tab="facilities">
      <%= link html_escape({:safe,"<i class='hospital icon'></i>Go to Facilities Page"}), to: admin_facility_path(@conn, :index), class: "ui fluid large teal submit button", target: "_blank" %>
    </div>
    <div class="ui tab segment" data-tab="payment-methods">
      <h4 class="ui dividing header">Payment Methods</h4>
      <div class="ui relaxed list">
          <%= for payment_type <- @payment_types do %>
          <div class="item">
            <i class="large caret right icon"></i>
            <div class="content">
              <div class="header">
                <div class="ui yellow label">
                  <%= payment_type.name %>
                </div>
              </div>
            </div>
        </div>
        <%= end %>
      </div>
      <h4 class="ui dividing header">Add Payment Method</h4>
      <%= render "payment_type.html", changeset: @payment_type_changeset,
                        action: admin_setting_path(@conn, :create_payment_type) %>

    </div>

  </div>
</div>

web/templates/admin_setting/membership_category.html.eex
<%= form_for @changeset, @action, [class: "ui form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :membership_category_name, "Membership Category", class: "control-label" %>
    <%= text_input f, :membership_category_name, class: "form-control" %>
    <%= error_tag f, :membership_category_name %>
  </div>

  <div class="field">
    <%= submit html_escape({:safe,"<i class='plus icon'></i>Membership Category"}), class: "ui pink submit button" %> 
  </div>
<% end %>

web/templates/admin_setting/membership_type.html.eex
<%= form_for @changeset, @action, [class: "ui form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :membership_type_name, "Membership Type", class: "control-label" %>
    <%= text_input f, :membership_type_name, class: "form-control" %>
    <%= error_tag f, :membership_type_name %>
  </div>

  <div class="field">
    <%= submit html_escape({:safe,"<i class='plus icon'></i>Membership Type"}), class: "ui pink submit button" %>
  </div>
<% end %>

web/templates/admin_setting/payment_type.html.eex
<%= form_for @changeset, @action, [class: "ui form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :name, "Payment Method", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="field">
    <%= submit html_escape({:safe,"<i class='plus icon'></i>Payment Method"}), class: "ui pink submit button" %>
  </div>
<% end %>

web/templates/admin_setting/register.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="ui form error">
    <div class="field">
      <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
      <%= error_tag f, :email %>
    </div>

    <div class="field">
      <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
      <%= error_tag f, :username %>
    </div>

    <div class="fields">
      <div class="eight wide field">
        <%= password_input f, :password, placeholder: "Password",  class: "form-control input" %>
        <%= error_tag f, :password %>
      </div>
      <div class="eight wide field">
        <%= password_input f, :password_confirmation, placeholder: "Repeat Password",  class: "form-control input" %>
        <%= error_tag f, :password_confirmation %>
      </div>
    </div>

    <%= if @changeset.action do %>
      <div class="ui error message">Oops, something went wrong! Please check the errors above.</div>
    <% end %>

    <%= submit "Add", class: "ui fluid large teal submit button" %>
  </div>
<% end %>