web/router.ex
defmodule MsqhPortal.Router do
  use MsqhPortal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MsqhPortal.Auth, repo: MsqhPortal.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_layout do
    plug MsqhPortal.Notification, repo: MsqhPortal.Repo
    plug :put_layout, {MsqhPortal.LayoutView, :admin}
  end

  pipeline :user_layout do
    plug MsqhPortal.Notification, repo: MsqhPortal.Repo
    plug :put_layout, {MsqhPortal.LayoutView, :user}
  end

  pipeline :login_layout do
    plug :put_layout, {MsqhPortal.LayoutView, :login}
  end

  pipeline :register_layout do
    plug :put_layout, {MsqhPortal.LayoutView, :register}
  end

  scope "/", MsqhPortal do
    pipe_through [:browser, :login_layout]

    get "/", LoginController, :index
    get "/change", LoginController, :change
    post "/send_email", LoginController, :change_password
    get "/reset/:id", LoginController, :reset
    get "/admin", AdminLoginController, :index
    get "/admin/change", AdminLoginController, :change
  end

  scope "/register", MsqhPortal do
    pipe_through [:browser, :register_layout]

    get "/", UserController, :new
    get "/admin", AdminController, :new
    post "/admin", AdminController, :create
    post "/", UserController, :create
  end

  scope "/", MsqhPortal do
    pipe_through [:browser, :user_layout] # Use the default browser stack

    resources "/user_enquiries", UserEnquiryController
    get "/user_enquiries/reply/:id", UserEnquiryController, :reply
    post "/user_enquiries/reply", UserEnquiryController, :send_reply
    patch "/user_enquiries/:id", UserEnquiryController, :response
    put "/user_enquiries/:id", UserEnquiryController, :response

    resources "/payments", PaymentController
    resources "/memberships", MembershipController
    resources "/facilities", FacilityController
    resources "/dashboard", UserController, only: [:index]
    get "/profile", ProfileController, :index
    get "/profile/edit", ProfileController, :edit
    patch "/profile/:id", ProfileController, :update
    put "/profile/:id", ProfileController, :update
    get "/payment", UserPaymentController, :index
    resources "/membership", UserMembershipController, only: [:index, :new, :create]
    get "/membership/edit/:id", UserMembershipController, :edit
    patch "/membership/:id", UserMembershipController, :update
    put "/membership/:id", UserMembershipController, :update
    resources "/membership/payment", UserMembershipPaymentController, only: [:index, :new, :create, :show]
    get "/membership/payment/edit/:id", UserMembershipPaymentController, :edit
    patch "/membership/payment/:id", UserMembershipPaymentController, :update
    put "/membership/payment/:id", UserMembershipPaymentController, :update
    get "/help", HelpController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/activation/:confirm_id", ActivationController, :confirm
    get "/events", UserEventController, :index
    get "/vouchers", UserRebateController, :index
    get "/resources", UserResourceController, :index

  end

  scope "/admin", MsqhPortal do
    pipe_through [:browser, :admin_layout] # Use the default browser stack

    resources "/dashboard", AdminController, only: [:index, :new, :show, :delete, :update, :create]
    get "/dashboard/change/:id", AdminController, :change
    put "/dashboard/change_password/:id", AdminController, :change_password
    get "/dashboard/edit/:id", AdminController, :edit
    resources "/prices", DefaultPriceController
    resources "/notifications", AdminMembershipSettingController
    resources "/membership_type", MembershipTypeController
    resources "/membership_category", MembershipCategoryController
    resources "/payments", PaymentLogController
    post "/search", AdminController, :search
    get "/approve/:id", AdminController, :approve
    patch "/approve/:id", AdminController, :approve
    put "/approve/:id", AdminController, :approve
    put "/verify/payment", AdminController, :verify
    post "/verify/payment", AdminController, :verify
    resources "/facilities", AdminFacilityController, only: [:index, :new, :show, :delete, :update, :create]
    get "/facilities/edit/:id", AdminFacilityController, :edit
    get "/facilities/package/edit/:id", AdminFacilityController, :edit_package
    patch "/facilities/package/update/:id", AdminFacilityController, :update_package
    put "/facilities/package/update/:id", AdminFacilityController, :update_package
    get "/settings", AdminSettingController, :index
    put "/settings/expiration_notification", AdminSettingController, :edit_expiration_notification
    post "/settings/membership_type", AdminSettingController, :create_membership_type
    post "/settings/membership_category", AdminSettingController, :create_membership_category
    post "/settings/default_price", AdminSettingController, :create_default_price
    post "/settings/payment_type", AdminSettingController, :create_payment_type
    delete "/settings/admin/:id", AdminSettingController, :delete_admin
    patch "/settings/payment_type/:id", AdminSettingController, :update_payment_type
    put "/settings/payment_type/:id", AdminSettingController, :update_payment_type
    post "/settings/admin", AdminSettingController, :create_admin
    get "/rebates", AdminRebateController, :index
    resources "/events", AdminEventController, only: [:index, :new, :show, :delete, :update, :create]
    get "/events/edit/:id", AdminEventController, :edit
    post "/events/voucher/create", AdminEventController, :voucher_create
    resources "/manage/vouchers", VoucherController
    resources "/enquiries", AdminEnquiryController
    get "/enquiries/reply/:id", AdminEnquiryController, :reply
    post "/enquiries/reply", AdminEnquiryController, :send_reply
    resources "/manage/responses", EnquiryResponseController
    resources "/resources", AdminResourceController, only: [:index, :new, :show, :delete, :update, :create]
    get "/resources/edit/:id", AdminResourceController, :edit
    resources "/manage/resources/permissions", ResourcePermissionsController
    resources "/packages", PackageController, only: [:index, :new, :show, :delete, :update, :create]
    get "/packages/edit/:id", PackageController, :edit

    resources "/sessions", AdminSessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MsqhPortal do
  #   pipe_through :api
  # end
end

web/controllers/user_payment_controller.ex
defmodule MsqhPortal.UserPaymentController do
  use MsqhPortal.Web, :controller

  alias MsqhPortal.PaymentLog
  @doc """
  Display:
  - Past payments i.e. paid_date, invoice_sent, payment_method, amount, receipt (PAYMENTS table)
  - Membership category (MEMBERSHIP table)
  - Invoice_sent & receipt has PDF (Admin creates file_path first)
  - Upload/edit proof of payment
  """
  def index(conn, params) do
    if conn.assigns.current_user do
      params_with_page_size = Enum.into(%{"page_size" => 5}, params)
      id = conn.assigns.current_user.id      

      payment_history = PaymentLog
      |> where([member_id: ^id])
      |> order_by(desc: :updated_at)
      |> preload([:membership, :membership_category, :membership_type, :package, :package_discount, :facility, :admin, :payment_type])
      |> Repo.paginate(params_with_page_size)

      render conn, "index.html", payment_history: payment_history
    else
      conn
      |> redirect(to: login_path(conn, :index))
    end
  end
end

web/views/user_payment_view.ex
defmodule MsqhPortal.UserPaymentView do
  use MsqhPortal.Web, :view
  import Scrivener.HTML
end

web/templates/user_payment/index.html.eex
<div class="ui grid">
  <!--the vertical side menu-->
  <div class="four wide column">
      <div class="verticalMenu">
          <div class="ui vertical pointing menu fluid">
              <%= link html_escape({:safe, "<i class='home icon'></i>Home"}), to: user_path(@conn, :index), class: "item" %>
              <%= link html_escape({:safe, "<i class='user icon'></i>Profile"}), to: profile_path(@conn, :index), class: "item" %>
              <%= link html_escape({:safe, "<i class='payment icon'></i>Payment History"}), to: user_payment_path(@conn, :index), class: "active teal item" %>
              <%= link html_escape({:safe, "<i class='users icon'></i>Renew Membership"}), to: user_membership_path(@conn, :index), class: "item" %>
              <%= link html_escape({:safe, "<i class='calendar icon'></i>Events"}), to: user_event_path(@conn, :index), class: "item" %>
              <%= link html_escape({:safe, "<i class='birthday icon'></i>Vouchers"}), to: user_rebate_path(@conn, :index), class: "teal item" %>
              <%= link html_escape({:safe, "<i class='university icon'></i>Resources"}), to: user_resource_path(@conn, :index), class: "item" %>
              <%= link html_escape({:safe, "<i class='info icon'></i>Help"}), to: user_enquiry_path(@conn, :index), class: "item" %>
          </div>
      </div>
  </div>

  <!--the main content-->
  <div class="twelve wide column">
    <div class="pageHeader">
      <div class="segment">
        <h3 class="ui dividing header">
          <i class="large payment icon"></i>
          <div class="content">Payment History
          </div>
        </h3>
      </div>
<%= unless Enum.count(@payment_history) < 1 do %>
    <table class="ui celled table">
      <thead>
        <tr>
          <th>Facility</th>
          <th>Membership Category</th>
          <th>Membership Type</th>
          <th>Annual Fee</th>
          <th>Membership Expiration Date</th>
          <th>Proof of Payment</th>
          <th>Receipt</th>
          <th>Verified</th>
        </tr>
      </thead>
      <tbody>
    <%= for payment <- @payment_history do %>
        <tr>
          <td><%= payment.facility.facility_name %></td>
          <td><%= payment.membership_category.membership_category_name %></td>
          <td>
            <%= unless is_nil(payment.membership_type) do %>
              <%= payment.membership_type.membership_type_name %>
              <%= else %>
              -
            <%= end %>
          </td>
          <td>
            <%= unless is_nil(payment.package.life_membership_price) do %>
              <%= payment.package.life_membership_price %>
            <%= end %>
            <%= unless is_nil(payment.package.new_member_annual_price) do %>
              <%= payment.package.new_member_annual_price %>
            <%= end %>
            <%= unless is_nil(payment.package.renewal_existing_member_annual_price) do %>
              <%= payment.package.renewal_existing_member_annual_price %>
            <%= end %>
          </td>
          <td><%= unless is_nil(payment.membership.active_to) do %><%= Timex.format!(payment.membership.active_to, "%b %d, %Y", :strftime) %><%= else %>-<%= end %></td>
          <td>
            <%= unless is_nil(payment.membership.proof_payment_path) do %>
            <%= link payment.payment_type.name, to: MsqhPortal.ProofPayment.url({payment.membership.proof_payment_path, payment.membership}, :original)
            |> String.split_at(12)
            |> Tuple.delete_at(0)
            |> Tuple.to_list
            |> Enum.join, target: "_blank"  %>
            <%= else %>
            -
          <%= end %>
          </td>
          <%= unless is_nil(payment.receipt_path) do %>
          <td class="ui center aligned header">
            <%= unless is_nil(payment.receipt_path) do %>
            <%= link html_escape({:safe, "<i class='file pdf outline icon'></i>"}), to: MsqhPortal.Receipt.url({payment.receipt_path, payment.membership}, :original)
            |> String.split_at(12)
            |> Tuple.delete_at(0)
            |> Tuple.to_list
            |> Enum.join, target: "_blank"  %>
              <%= else %>
              -
            <%= end %>
          </td>
          <%= else %>
          <td>-</td>
          <%= end %>
          <td class="ui center aligned header">
            <%= if payment.membership.payment_verified do %>
              <i class='green checkmark icon'></i>
              <%= else %>
              <i class='red remove icon'></i>
            <%= end %>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>
    <% else %>
    <div class="ui relaxed divided list">
    No payments logged
    </div>
    <% end %>
    <%= pagination_links @payment_history, view_style: :semantic%>
    </div>
  </div>
</div>